services:
  ffpanel:
    extends:
      file: docker-compose.common.yml
      service: ffpanel
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FFPANEL_IMAGE:-ffpanel:1.0.0-rk3588}
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
    privileged: true
